@url=http://localhost:7474/api
@json=Content-Type: application/json
@xx=Content-Type: application/x-www-form-urlencoded

### 请求入口
get {{url}}

### 注册入口
post {{url}}/register

{{json}}

{
  "username": "user4",
  "password": "123456"
}

### 登录接口 -- why 用不了
post {{url}}/login

{{json}}

{
  "username": "user4",
  "password": "123456"
}

### 查询所有用户
get {{url}}/users

### 根据 token 查询对应的用户
get {{url}}/profile

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMWQzZGE4MWI3Y2ZlMmJkODRjMTYzYyIsImlhdCI6MTYxMjUzMTg0NX0.zD_0uCDFFBo8yf-gzVEUc5CiCMFiiD7I9saFgpJlId0 
